name: pycuda_plus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pycuda
  - numpy
  - pytest
  - sphinx
  - platformdirs
  - setuptools
  - pip
  - six
  - matplotlib
  - seaborn
  - pandas
  - cupy
